### ISSUE TITLE
Typo in Cheatsheets / Markdown / Alignment

### ISSUE THREAD

**Issue by talllguy** [MichaelCurrin/dev-cheatsheets#44]
Hi, love the repo! All around great work. I found just a minor typo on the [Cheatsheets / Markdown / Alignment](https://michaelcurrin.github.io/dev-cheatsheets/cheatsheets/markdown/alignment.html) page ([code here](https://github.com/MichaelCurrin/dev-cheatsheets/blob/a9451ddb5355362898f26663ef638f677521c8f6/cheatsheets/markdown/alignment.md?plain=1#L4)).

> Using markdown on GitHub, you can't styling with CSS. It gets ignored.

I think this should say:

"Using markdown on GitHub, you can't _style_ with CSS. It gets ignored."

That's it, thanks!

**Comment by MichaelCurrin** [comment]
Fixed and reworded, thanks
