### ISSUE TITLE
github-actions output deprecated

### ISSUE THREAD

**Issue by diepes** [MichaelCurrin/dev-cheatsheets#46]
dev-cheatsheets/cheatsheets/ci-cd/github-actions/persist.md

Examples setting output with stdout echo is deprecated now.

see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by MichaelCurrin** [comment]
Thanks!

**Comment by MichaelCurrin** [comment]
Thanks! I made the change in my file
